### ISSUE TITLE
Decryption failing after upgrading to Spring Boot 3.2.2

### ISSUE THREAD

**Issue by seaswaraiyer** [mptechnology/spring-crypto-cli#2]
Hello, I generated the encrypted password and used it in a Spring Boot 2.7.0 project that used the spring cloud starter library 3.1.7(which uses spring-security-crypto 5.7.1) and it worked fine.
I upgraded to Spring Boot 3.2.2 today. I'm now using the spring cloud starter library 4.1.0(which uses spring-security-crypto 6.2.1) and the decryption failed with the below error message.

This is how I have it specified in the application.properties file.
spring.security.oauth2.client.registration.google.client-id={cipher}c2d41dd6dde228.....

Here is the full stack trace

16:54:34.069 [restartedMain] ERROR org.springframework.boot.SpringApplication -- Application run failed
java.lang.IllegalStateException: Cannot decrypt: key=spring.security.oauth2.client.registration.google.client-id
	at org.springframework.cloud.bootstrap.encrypt.AbstractEnvironmentDecrypt.decrypt(AbstractEnvironmentDecrypt.java:158)
	at org.springframework.cloud.bootstrap.encrypt.AbstractEnvironmentDecrypt.lambda$decrypt$0(AbstractEnvironmentDecrypt.java:136)
	at java.base/java.util.LinkedHashMap.replaceAll(LinkedHashMap.java:731)
	at org.springframework.cloud.bootstrap.encrypt.AbstractEnvironmentDecrypt.decrypt(AbstractEnvironmentDecrypt.java:131)
	at org.springframework.cloud.bootstrap.encrypt.AbstractEnvironmentDecrypt.decrypt(AbstractEnvironmentDecrypt.java:70)
	at org.springframework.cloud.bootstrap.encrypt.TextEncryptorUtils.decrypt(TextEncryptorUtils.java:52)
	at org.springframework.cloud.bootstrap.encrypt.DecryptEnvironmentPostProcessor.postProcessEnvironment(DecryptEnvironmentPostProcessor.java:66)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:109)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:94)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:149)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:137)
	at org.springframework.boot.context.event.EventPublishingRunListener.multicastInitialEvent(EventPublishingRunListener.java:136)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:81)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:64)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:63)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:369)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:329)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at com.saibisa.IndHealApplication.main(IndHealApplication.java:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)
Caused by: java.lang.UnsupportedOperationException: No decryption for FailsafeTextEncryptor. Did you configure the keystore correctly?
	at org.springframework.cloud.bootstrap.encrypt.TextEncryptorUtils$FailsafeTextEncryptor.decrypt(TextEncryptorUtils.java:188)
	at org.springframework.cloud.bootstrap.encrypt.AbstractEnvironmentDecrypt.decrypt(AbstractEnvironmentDecrypt.java:143)
	... 29 common frames omitted

**Comment by mpstadler** [comment]
Well i guess this would rather be an issue for the [spring-cloud(-commons)](https://github.com/spring-cloud/spring-cloud-commons) team, because spring-crypto-cli is basically just a wrapper around their encryption/decryption functionality.

However using this spring-crypto-cli you could check if your encrypted password can be decrypted given your `encrypt.key`. 
If this is the case I would recommend to check if if you have properly set the `encrypt.key` within your application at startup time.

**Comment by seaswaraiyer** [comment]
Thanks, Jacques. It was my mistake. I copied the project in eclipse and the environment variable configuration in eclipse didn't get copied over. Again, i'm really sorry about this.
ThanksSaraswathi
    On Thursday, February 1, 2024 at 05:57:17 PM GMT+5:30, Jacques Stadler ***@***.***> wrote:  
 
 


Well i guess this would rather be an issue for the spring-cloud(-commons) team, because spring-crypto-cli is basically just a wrapper around their encryption/decryption functionality.

However using this spring-crypto-cli you could check if your encrypted password can be decrypted given your encrypt.key.
If this is the case I would recommend to check if if you have properly set the encrypt.key within your application at startup time.
